import { db } from "../lib/db/prisma";
import { ALL_PERMISSIONS } from "../lib/rbac/permissions";

// --- Mock Clerk & Next.js to run standalone ---
import Module from "module";
const originalRequire = Module.prototype.require;
(Module.prototype as any).require = function(request: string) {
  if (request === "@clerk/nextjs/server") {
    return {
      auth: async () => ({ userId: (global as any).__TEST_USER_ID__ }),
      currentUser: async () => ({
        id: (global as any).__TEST_USER_ID__,
        emailAddresses: [{ emailAddress: "test@example.com" }]
      })
    };
  }
  if (request === "next/server" || request === "next/headers") {
    return {
      NextRequest: class {},
      NextResponse: class {},
      cookies: () => ({ get: () => null })
    };
  }
  return originalRequire.apply(this, arguments as any);
};

// Now import our middleware
const { checkPermission } = require("../lib/rbac/checkPermission");
const { ApiError } = require("../lib/workspace/resolveWorkspace");

async function main() {
  console.log("Setting up isolated RBAC test environment...");
  
  // Create 4 dummy users
  const roleNames = ["Owner", "Admin", "Manager", "Member"];
  const testUsers = [];
  
  for (const rn of roleNames) {
    const u = await db.user.create({
      data: {
        id: `test_user_${rn.toLowerCase()}_${Date.now()}`,
        clerkId: `clerk_${rn.toLowerCase()}_${Date.now()}`,
        email: `test_${rn.toLowerCase()}@example.com`,
        name: `Test ${rn}`,
      }
    });
    testUsers.push(u);
  }
  
  const ownerUser = testUsers[0];
  
  // Create a workspace
  const workspace = await db.workspace.create({
    data: {
      name: "RBAC Test Workspace",
      slug: `rbac-test-${Date.now()}`,
      ownerId: ownerUser.id,
    }
  });

  // Fetch the created system roles automatically generated by resolving the workspace
  // Wait, the system roles are only seeded if we invoke resolveWorkspace on creation!
  // Let's manually trigger resolveWorkspace once as the owner, which seeds the roles safely
  (global as any).__TEST_USER_ID__ = ownerUser.id;
  await checkPermission(workspace.slug, "project.view");

  const roles = await db.role.findMany({ where: { workspaceId: workspace.id } });

  // Add the other 3 members with their corresponding roles
  for (let i = 1; i < roleNames.length; i++) {
    const roleDb = roles.find(r => r.name === roleNames[i]);
    if (!roleDb) throw new Error(`Role ${roleNames[i]} not found!`);
    
    await db.workspaceMember.create({
      data: {
        workspaceId: workspace.id,
        userId: testUsers[i].id,
        roleId: roleDb.id
      }
    });
  }

  console.log(`\nStarting execution tests across ${ALL_PERMISSIONS.length} permissions and ${roleNames.length} roles...\n`);
  
  let mdTable = "| Role | Permission Key | Expected | Actual | Status |\n";
  mdTable += "|------|----------------|----------|--------|--------|\n";
  
  for (let i = 0; i < roleNames.length; i++) {
    const rName = roleNames[i];
    const user = testUsers[i];
    const roleDb = roles.find(r => r.name === roleNames[i]);
    const allowedPerms: string[] = roleDb ? (roleDb.permissions as string[]) : [];

    // Set the auth context for this user
    (global as any).__TEST_USER_ID__ = user.id;

    for (const perm of ALL_PERMISSIONS) {
      const expectedToPass = rName === "Owner" ? true : allowedPerms.includes(perm);
      let actualPass = false;
      let actualMsg = "Denied (403)";
      
      try {
        await checkPermission(workspace.slug, perm);
        actualPass = true;
        actualMsg = "Allowed (OK)";
      } catch (err: any) {
        if (err.statusCode === 403 || err.message === "Forbidden") {
          actualPass = false;
        } else {
          // Unexpected error
          actualMsg = `Error: ${err.message}`;
        }
      }
      
      const statusIcon = (expectedToPass === actualPass) ? "✅ Pass" : "❌ FAIL";
      
      mdTable += `| ${rName} | \`${perm}\` | ${expectedToPass ? 'Allowed' : 'Denied'} | ${actualMsg} | ${statusIcon} |\n`;
    }
  }

  console.log(mdTable);

  const fs = require('fs');
  fs.writeFileSync('artifacts/rbac_verification_matrix.md', mdTable);
  console.log("\nResults have been generated in artifacts/rbac_verification_matrix.md");

  // Cleanup DB
  console.log("\nCleaning up test data...");
  await db.workspace.delete({ where: { id: workspace.id } });
  await db.user.deleteMany({ where: { id: { in: testUsers.map(u => u.id) } } });
}

main()
  .catch(console.error)
  .finally(async () => {
    await db.$disconnect();
    process.exit(0);
  });
